apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django
        image: your-django-image:latest  # Replace with your image
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_HOST
          value: postgresql
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: mydb
        - name: DATABASE_USER
          value: myuser
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: password
---
apiVersion: v1
kind: LoadBalancer
metadata:
  name: django-service
spec:
  type: NodePort
  selector:
    app: django-app
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
